let WAITFOR = 2
music.setVolume(255)
let SA = 256
let RE = SA * (9 / 8)
let GA = RE * (10 / 9)
let MA = GA * (16 / 15)
let PA = MA * (9 / 8)
let DHA = PA * (10 / 9)
let NI = DHA * (9 / 8)
let SAA = NI * (16 / 15)
basic.forever(function () {
    music.playTone(SA, music.beat(BeatFraction.Whole))
    basic.pause(WAITFOR)
    music.playTone(RE, music.beat(BeatFraction.Whole))
    basic.pause(WAITFOR)
    music.playTone(GA, music.beat(BeatFraction.Whole))
    basic.pause(WAITFOR)
    music.playTone(MA, music.beat(BeatFraction.Whole))
    basic.pause(WAITFOR)
    music.playTone(PA, music.beat(BeatFraction.Whole))
    basic.pause(WAITFOR)
    music.playTone(DHA, music.beat(BeatFraction.Whole))
    basic.pause(WAITFOR)
    music.playTone(NI, music.beat(BeatFraction.Whole))
    basic.pause(WAITFOR)
    music.playTone(SAA, music.beat(BeatFraction.Whole))
    basic.pause(WAITFOR)
    music.playTone(SAA, music.beat(BeatFraction.Whole))
    basic.pause(WAITFOR)
    music.playTone(NI, music.beat(BeatFraction.Whole))
    basic.pause(WAITFOR)
    music.playTone(DHA, music.beat(BeatFraction.Whole))
    basic.pause(WAITFOR)
    music.playTone(PA, music.beat(BeatFraction.Whole))
    basic.pause(WAITFOR)
    music.playTone(MA, music.beat(BeatFraction.Whole))
    basic.pause(WAITFOR)
    music.playTone(GA, music.beat(BeatFraction.Whole))
    basic.pause(WAITFOR)
    music.playTone(RE, music.beat(BeatFraction.Whole))
    basic.pause(WAITFOR)
    music.playTone(SA, music.beat(BeatFraction.Whole))
    basic.pause(WAITFOR)
})
