// SA-RE-GA-MA-PA
let WAITFOR = 1000
music.setVolume(255)
let SA = 256
let RE = SA * (9 / 8)
let GA = RE * (10 / 9)
let MA = GA * (16 / 15)
let PA = MA * (9 / 8)
let DHA = PA * (10 / 9)
let NI = DHA * (9 / 8)
let SAA = NI * (16 / 15)
basic.forever(function () {
    music.playTone(SA, WAITFOR)
    music.playTone(RE, WAITFOR)
    music.playTone(GA, WAITFOR)
    music.playTone(MA, WAITFOR)
    music.playTone(PA, WAITFOR)
    music.playTone(DHA, WAITFOR)
    music.playTone(NI, WAITFOR)
    music.playTone(SAA, WAITFOR)
    music.playTone(SAA, WAITFOR)
    music.playTone(NI, WAITFOR)
    music.playTone(DHA, WAITFOR)
    music.playTone(PA, WAITFOR)
    music.playTone(MA, WAITFOR)
    music.playTone(GA, WAITFOR)
    music.playTone(RE, WAITFOR)
    music.playTone(SA, WAITFOR)
})
